# Generated by Django 5.0.6 on 2025-04-02 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eateries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='code',
            field=models.CharField(max_length=8, verbose_name='Code'),
        ),
    ]
