# Generated by Django 5.0.6 on 2025-04-02 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eateries', '0002_alter_currency_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='wallpaper',
            field=models.ImageField(blank=True, null=True, upload_to='wallpapers/', verbose_name='Wallpaper'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='wifi',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/', verbose_name='QR code'),
        ),
    ]
