# Generated by Django 5.0.6 on 2025-04-02 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eateries', '0003_alter_category_image_alter_organization_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='wifi_password',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organizations', to='eateries.wifi', verbose_name='Wi-Fi password'),
        ),
    ]
