# Generated by Django 5.0.6 on 2025-04-10 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eateries', '0007_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='type',
            field=models.CharField(choices=[('on_table', 'Dine in'), ('take_away', 'Take away')], default='on_table', max_length=10, verbose_name='Type'),
        ),
    ]
