# Generated by Django 5.0.6 on 2025-04-11 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eateries', '0008_order_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='weight_text',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Weight text'),
        ),
    ]
