# Generated by Django 5.0.6 on 2025-04-11 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eateries', '0009_product_weight_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='weight',
        ),
    ]
