# Generated by Django 5.0.6 on 2025-04-11 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eateries', '0010_remove_product_weight'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='weight_text',
            new_name='weight',
        ),
    ]
