# Generated by Django 5.0.6 on 2025-04-11 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eateries', '0013_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='eateries.userprofile', verbose_name='User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='user',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='organizations', to='eateries.userprofile', verbose_name='User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Is active'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sms_code',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='SMS code'),
        ),
    ]
