# Generated by Django 5.0.6 on 2025-04-12 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eateries', '0014_order_user_organization_user_userprofile_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
