# Generated by Django 5.0.6 on 2025-04-20 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eateries', '0016_productorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='auth_token',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Auth Token'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='token_expiry',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Token Expiry'),
        ),
    ]
