# Generated by Django 5.0.6 on 2025-04-21 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eateries', '0017_userprofile_auth_token_userprofile_token_expiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='working_days',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Working days'),
        ),
        migrations.AddField(
            model_name='organization',
            name='working_hours',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Working hours'),
        ),
    ]
