# Generated by Django 5.0.6 on 2025-04-22 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eateries', '0018_organization_working_days_organization_working_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_authenticated',
            field=models.BooleanField(default=False, verbose_name='is authenticated'),
        ),
    ]
