# Generated by Django 5.0.6 on 2025-04-25 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eateries', '0019_userprofile_is_authenticated'),
    ]

    operations = [
        migrations.AddField(
            model_name='wifi',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eateries.organization'),
        ),
    ]
