# Generated by Django 5.0.6 on 2025-04-25 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eateries', '0021_alter_wifi_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='wifi_password',
        ),
    ]
