# Generated by Django 5.0.6 on 2025-04-28 03:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eateries', '0022_remove_organization_wifi_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message='Invalid phone number.', regex='^\\+998\\d{9}$')], verbose_name='Phone number'),
        ),
    ]
