# Generated by Django 5.0.6 on 2025-04-29 06:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eateries', '0023_alter_userprofile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='phone_number',
            field=models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message='Invalid phone number.', regex='^\\+998\\d{9}$')], verbose_name='Phone number'),
        ),
    ]
